import { nanoid } from 'nanoid';

// Generate a verification hash for a document
export function generateVerificationHash(): string {
  // Use nanoid for URL-safe unique IDs
  // Format: bmoh-xxxx-xxxx-xxxx (16 chars)
  const id = nanoid(12);
  return `bmoh-${id.slice(0, 4)}-${id.slice(4, 8)}-${id.slice(8, 12)}`;
}

// Mirror the shape `generateVerificationHash()` actually emits: a `bmoh-` prefix
// followed by three nanoid-URL-safe segments of 4 characters joined by `-`.
// Nanoid's default alphabet is `A-Za-z0-9_-`. Server-side validation gives
// `/api/documents/[hash]` (and any other endpoint that takes a hash) a cheap
// way to reject obviously-invalid inputs before doing a database lookup — same
// trust-boundary principle as the prior server-side `wordCount`, `title`,
// `writingTimeMs`, and trace-size gates: the server is the canonical source
// for what it admits, and we never spend an external roundtrip on input that
// can't have been generated by us.
const HASH_PATTERN = /^bmoh-[A-Za-z0-9_-]{4}-[A-Za-z0-9_-]{4}-[A-Za-z0-9_-]{4}$/;

// Accept `unknown` and narrow it to `string` so API/browser response boundaries
// can validate an untrusted hash without first lying to TypeScript about its
// type. Existing string callers keep the same boolean behavior.
export function isValidVerificationHash(hash: unknown): hash is string {
  return typeof hash === 'string' && HASH_PATTERN.test(hash);
}
